name: fetch-overleaf-resume

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:
  push:
    paths:
    - .github/workflows/update-resume.yml

jobs:
  fetch-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: Sbrjt/overleaf-resume-syncer@main
        with:
          overleaf_url: 'https://www.overleaf.com/read/nsgsskwncdmy#a859ac'
          gdrive_link: 'https://drive.google.com/file/d/17E9HqUxaU0sn_9NjeAhz6ck2GKRhyHcm/view?usp=drive_link'
          github_token: ${{ secrets.GITHUB_TOKEN }}
