name: fetch-overleaf-resume

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:
  push:

jobs:
  fetch-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: Sbrjt/overleaf-resume-downloader@v1
        with:
          overleaf_url: 'https://www.overleaf.com/read/nsgsskwncdmy#a859ac'
          github_token: ${{ secrets.GITHUB_TOKEN }}
