name: fetch-overleaf-resume

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:
  push:
    paths:
    - .github/workflows/update-resume.yml

jobs:
  fetch-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: Sbrjt/overleaf-resume-downloader@main
        with:
          overleaf_url: 'https://www.overleaf.com/read/nsgsskwncdmy#a859ac' # also change the iframe src in index.html 
          github_token: ${{ secrets.GITHUB_TOKEN }}
